/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : TimeDateLdd1.c
**     Project     : RCS_Box_2.2
**     Processor   : MK22FN512VLH12
**     Component   : TimeDate_LDD
**     Version     : Component 01.007, Driver 01.01, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-02-06, 20:24, # CodeGen: 0
**     Abstract    :
**          This component "TimeDate_LDD" implements real time and date.
**          The component requires a periodic interrupt generator: timer
**          compare or reload register or timer-overflow interrupt
**          (of free running counter). User can select precision of
**          selected timer.
**          The component supports alarm with event OnAlarm and every second
**          event OnSecond is also available.
**          This TimeDate component provides a high level API for unified
**          hardware access to various timer devices using the TimerUnit
**          component.
**     Settings    :
**          Component name                                 : TimeDateLdd1
**          Periodic interrupt source                      : FTM1_MOD
**          Counter                                        : FTM1_CNT
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_FTM1
**            Interrupt priority                           : medium priority
**          Resolution                                     : 122.070312 µs
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Time                                         : 00:00:00
**            Date                                         : 2008-01-01
**            Alarm time                                   : 00:00:00
**            Auto initialization                          : yes
**            Event mask                                   : 
**              OnAlarm                                    : Disabled
**              OnSecond                                   : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**          Referenced components                          : 
**            Linked TimerUnit                             : TU2
**     Contents    :
**         Init    - LDD_TDeviceData* TimeDateLdd1_Init(LDD_TUserData *UserDataPtr);
**         SetTime - LDD_TError TimeDateLdd1_SetTime(LDD_TDeviceData *DeviceDataPtr,...
**         GetTime - LDD_TError TimeDateLdd1_GetTime(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file TimeDateLdd1.c
** @version 01.01
** @brief
**          This component "TimeDate_LDD" implements real time and date.
**          The component requires a periodic interrupt generator: timer
**          compare or reload register or timer-overflow interrupt
**          (of free running counter). User can select precision of
**          selected timer.
**          The component supports alarm with event OnAlarm and every second
**          event OnSecond is also available.
**          This TimeDate component provides a high level API for unified
**          hardware access to various timer devices using the TimerUnit
**          component.
*/         
/*!
**  @addtogroup TimeDateLdd1_module TimeDateLdd1 module documentation
**  @{
*/         

/* MODULE TimeDateLdd1. */

#include "TimeDateLdd1.h"
/* {Default RTOS Adapter} No RTOS includes */

#ifdef __cplusplus
extern "C" {
#endif 

/* Table of month length (in days) */
static const uint16_t NLY[12] = {31U,28U,31U,30U,31U,30U,31U,31U,30U,31U,30U,31U}; /* Non-leap-year */
static const uint16_t  LY[12] = {31U,29U,31U,30U,31U,30U,31U,31U,30U,31U,30U,31U}; /* Leap-year */

typedef struct {
  LDD_TDeviceData *LinkedDeviceDataPtr;
  bool EnUser;                         /* Enable/Disable device */
  uint32_t TotalHthL;                  /* Low part of software tick counter */
  uint32_t TotalHthH;                  /* High part of software tick counter (1 tick = 10ms) */
  uint16_t CntDay;                     /* Day counter */
  uint16_t CntMonth;                   /* Month counter */
  uint16_t CntYear;                    /* Year counter */
  uint16_t CntDOW;                     /* Sun - Sat counter */
  LDD_TUserData *UserDataPtr;          /* RTOS device data structure */
} TimeDateLdd1_TDeviceData;

typedef TimeDateLdd1_TDeviceData *TimeDateLdd1_TDeviceDataPtr; /* Pointer to the device data structure. */

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static TimeDateLdd1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;

/*
** ===================================================================
**     Method      :  TimeDateLdd1_Init (component TimeDate_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property ["Enable in init. code"] is set to "yes" value then
**         the device is also enabled (see the description of the
**         [Enable] method). In this case the [Enable] method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the [Deinit]
**         must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* TimeDateLdd1_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate device structure */
  TimeDateLdd1_TDeviceData *DeviceDataPrv;
  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  DeviceDataPrv->UserDataPtr = UserDataPtr; /* Store the RTOS device structure */
  DeviceDataPrv->TotalHthL = 0U;
  DeviceDataPrv->TotalHthH = 0U;       /* Software tick counter (1 tick = 10ms) */
  DeviceDataPrv->CntDay = 1U;          /* Day counter */
  DeviceDataPrv->CntMonth = 1U;        /* Month counter */
  DeviceDataPrv->CntYear = 2008U;      /* Year counter */
  DeviceDataPrv->CntDOW = 2U;          /* Sun - Sat counter */
  DeviceDataPrv->EnUser = TRUE;        /* Set the flag "device enabled" */
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_TimeDateLdd1_ID,DeviceDataPrv);
  DeviceDataPrv->LinkedDeviceDataPtr = TU2_Init((LDD_TUserData *)NULL);
  if (DeviceDataPrv->LinkedDeviceDataPtr == NULL) { /* Is initialization of TimerUnit unsuccessful? */
    /* Unregistration of the device structure */
    PE_LDD_UnregisterDeviceStructure(PE_LDD_COMPONENT_TimeDateLdd1_ID);
    /* Deallocation of the device structure */
    /* {Default RTOS Adapter} Driver memory deallocation: Dynamic allocation is simulated, no deallocation code is generated */
    return NULL;                       /* If so, then the TimeDate initialization is also unsuccessful */
  }
  return ((LDD_TDeviceData *)DeviceDataPrv); /* Return pointer to the device data structure */
}

/*
** ===================================================================
**     Method      :  TimeDateLdd1_SetTime (component TimeDate_LDD)
*/
/*!
**     @brief
**         Sets new time.
**         Note: All LDD_TimeDate_TTimeRec structure members must be
**         correctly filled in.
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure pointer returned by [Init] method.
**     @param
**         TimePtr         - Pointer to the time structure with
**                           new time to set.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_RANGE - Parameter out of range
*/
/* ===================================================================*/
LDD_TError TimeDateLdd1_SetTime(LDD_TDeviceData *DeviceDataPtr, LDD_TimeDate_TTimeRec *TimePtr)
{
  TimeDateLdd1_TDeviceData *DeviceDataPrv = (TimeDateLdd1_TDeviceData *)DeviceDataPtr;

  /* Parameter test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if ((TimePtr->Sec100 > 99U) || (TimePtr->Sec > 59U) || (TimePtr->Min > 59U) || (TimePtr->Hour > 23U)) { /* Test correctness of given time */
    return ERR_RANGE;                  /* If not correct then error */
  }
  if (DeviceDataPrv->EnUser) {         /* Is the component enabled now? */
    (void)TU2_Disable(DeviceDataPrv->LinkedDeviceDataPtr); /* Disable TimerUnit component */
  }
  DeviceDataPrv->TotalHthH = (360000UL * (uint32_t)TimePtr->Hour) + (6000U * (uint32_t)TimePtr->Min) + (100U * (uint32_t)TimePtr->Sec) + (uint32_t)TimePtr->Sec100; /* Load given time re-calculated to 10ms ticks into software tick counter */
  DeviceDataPrv->TotalHthL = 0U;
  if (DeviceDataPrv->EnUser) {         /* Is the component enabled? */
    (void)TU2_Enable(DeviceDataPrv->LinkedDeviceDataPtr); /* Enable TimerUnit */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  TimeDateLdd1_GetTime (component TimeDate_LDD)
*/
/*!
**     @brief
**         Returns actual time.
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure pointer returned by [Init] method.
**     @param
**         TimePtr         - Pointer to the time structure to
**                           fill with current time.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError TimeDateLdd1_GetTime(LDD_TDeviceData *DeviceDataPtr, LDD_TimeDate_TTimeRec *TimePtr)
{
  TimeDateLdd1_TDeviceData *DeviceDataPrv = (TimeDateLdd1_TDeviceData *)DeviceDataPtr;
  uint32_t Var1;                       /* Temporary copy of software tick counter */
  uint16_t Var2;                       /* Temporary variable */

  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  Var1 = DeviceDataPrv->TotalHthH;     /* Loading actual number of tens of ms */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  TimePtr->Sec100 = (uint16_t)(Var1 % 100U); /* Modulo 100 gives appropriate number of hundreds of seconds */
  Var1 = Var1 / 100U;                  /* Quotient gives total number of seconds then */
  TimePtr->Sec = (uint16_t)(Var1 % 60U); /* Modulo 60 gives appropriate number of seconds */
  Var2 = (uint16_t)(Var1 / 60U);       /* Quotient gives total number of minutes then */
  TimePtr->Min = (uint16_t)(Var2 % 60U); /* Modulo 60 gives appropriate number of minutes */
  TimePtr->Hour = (uint16_t)(Var2 / 60U); /* Quotient gives total number of hours then */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  TimeDateLdd1_TU2_OnCounterRestart (component TimeDate_LDD)
**
**     Description :
**         The method services the event of the linked component TU2 and 
**         eventually invokes event OnAlarm and OnSecond.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void TU2_OnCounterRestart(LDD_TUserData *UserDataPtr)
{
  TimeDateLdd1_TDeviceData *DeviceDataPrv = PE_LDD_DeviceDataList[PE_LDD_COMPONENT_TimeDateLdd1_ID];
  register uint32_t Val32;             /* Temporary variable */
  register const uint16_t *ptr;        /* Pointer to NLY/LY table */

  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  Val32 = DeviceDataPrv->TotalHthL + 0x03200000UL; /* Add timer period to the lower part of software timer counter */
  if (Val32 < DeviceDataPrv->TotalHthL) { /* Was there a carry from lower part into upper part of software timer counter? */
    DeviceDataPrv->TotalHthH++;        /* If yes then increment upper part of the software timer counter */
  }
  DeviceDataPrv->TotalHthL = Val32;    /* Write new value of the software timer counter */
  if (DeviceDataPrv->TotalHthH >= 0x0083D600UL) { /* Does the counter reach 24 hours? */
    DeviceDataPrv->TotalHthH -= 0x0083D600UL; /* If yes then reset it by subtracting exactly 24 hours */
    DeviceDataPrv->CntDOW++;           /* Increment Sun - Sat counter */
    if (DeviceDataPrv->CntDOW > 6U) {  /* Sun - Sat counter overflow? */
      DeviceDataPrv->CntDOW = 0U;      /* Set Sun - Sat counter on Sun */
    } 
    DeviceDataPrv->CntDay++;           /* Increment day counter */
    if (DeviceDataPrv->CntYear & 0x03U) { /* Is this year non-leap-one? */
      ptr = NLY;                       /* Set pointer to non-leap-year day table */
    }
    else {                             /* Is this year leap-one? */
      ptr = LY;                        /* Set pointer to leap-year day table */
    }
    ptr--;                             /* Decrement the pointer */
    if (DeviceDataPrv->CntDay > ptr[DeviceDataPrv->CntMonth]) { /* Day counter overflow? */
      DeviceDataPrv->CntDay = 1U;      /* Set day counter on 1 */
      DeviceDataPrv->CntMonth++;       /* Increment month counter */
      if (DeviceDataPrv->CntMonth > 12U) { /* Month counter overflow? */
        DeviceDataPrv->CntMonth = 1U;  /* Set month counter on 1 */
        DeviceDataPrv->CntYear++;      /* Increment year counter */
      }
    }
  }
}

/* END TimeDateLdd1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
