################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.c \
../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.d \
./ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/%.o: ../ARM.CMSIS.5.5.1/CMSIS/DSP/Source/FilteringFunctions/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g3 -DARM_MATH_CM4 -I"C:/Users/ndf30/RCS_workspace/RCS_Box_2.0/Static_Code/System" -I"C:\Users\ndf30\RCS_workspace\RCS_Box_2.0\ARM.CMSIS.5.5.1\CMSIS/Include" -I"C:/Users/ndf30/RCS_workspace/RCS_Box_2.0/Static_Code/PDD" -I"C:/Users/ndf30/RCS_workspace/RCS_Box_2.0/Static_Code/IO_Map" -I"C:\Freescale\KDS_v3\eclipse\ProcessorExpert/lib/Kinetis/pdd/inc" -I"C:/Users/ndf30/RCS_workspace/RCS_Box_2.0/Sources" -I"C:/Users/ndf30/RCS_workspace/RCS_Box_2.0/Generated_Code" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


